apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-clusterrole
rules:
- apiGroups: ["*"]
  resources: ["pods","replicasets","services","events"]
  verbs: ["get","list","watch"]
- apiGroups: ["*"]
  resources: ["deployments"]
  verbs: ["get","list","watch","patch","update"]
- apiGroups: ["*"]
  resources: ["pods/exec","pods/log"]
  verbs: ["get","list","watch","create"]
